export const mockedOptions = [
  { value: 1, label: "Neptunium" },
  { value: 2, label: "Plutonium" },
  { value: 3, label: "Americium" },
  { value: 4, label: "Curium" },
  { value: 5, label: "Berkelium" },
  { value: 6, label: "Californium" },
  { value: 7, label: "Einsteinium" },
  { value: 8, label: "Fermium" },
  { value: 9, label: "Mendelevium" },
  { value: 10, label: "Nobelium" },
  { value: 11, label: "Lawrencium" },
  { value: 12, label: "Rutherfordium" },
  { value: 13, label: "Dubnium" },
  { value: 14, label: "Seaborgium" },
  { value: 15, label: "Bohrium" },
  { value: 16, label: "Hassium" },
  { value: 17, label: "Meitnerium" },
  { value: 18, label: "Darmstadtium" },
  { value: 19, label: "Roentgenium" },
  { value: 20, label: "Copernicium" },
  { value: 21, label: "Nihonium" },
  { value: 22, label: "Flerovium" },
  { value: 23, label: "Moscovium" },
  { value: 24, label: "Livermorium" },
  { value: 25, label: "Tennessine" },
  { value: 26, label: "Oganesson" },
]
